### ISSUE TITLE
A few things missing.

### ISSUE THREAD

**Issue by JordanEJ** [Avangelista/CowabungaLiteWindows#5]
Loving this, however there are a few things missing:

- No Control center layout options
- Only some apps show in the theming section

**Comment by Avangelista** [comment]
Control Centre options will be added with an update. Regarding apps, it will list every app on your Home Screen, not App Library. So place apps you’d like to theme on the Home Screen.

**Comment by JordanEJ** [comment]
Ahh, that makes sense. Cheers. Silly me 😂
